apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx      # This MUST match the labels in your Deployment's pod template
  ports:
    - port: 80           # The port the service exposes internally
      targetPort: 80   # The port your container is actually listening on
      nodePort: 30007    # Optional: Range must be 30000-32767. If omitted, K8s assigns one.
      protocol: TCP
